version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      ginkgo:
        patterns:
          - github.com/onsi/ginkgo/v2
          - github.com/onsi/gomega
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "weekly"
