name: Build

permissions: { }

on:
  pull_request:
    branches: ['develop']
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths-ignore:
      - '.github/**'
      - 'charts/**'
      - 'LICENSE'
      - 'README.md'

jobs:

  Test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: stable
      - name: Install Dependencies
        run: go mod download
      - name: Test
        run: make test

  Build:
    needs: ['Test']
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      VERSION: latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: stable
      - name: Install Dependencies
        run: go mod download
      - name: Build
        run: make image
